### PR TITLE
feat: Change base deberta to large deberta

### PR DESCRIPTION
**Pull request by erendabanlioglu**
As @Timoeller s request.

### CODE REVIEW

**Review by Timoeller — APPROVED** [review]
LG!

reason is the large model performs better on out of domain data and people are more concerned with accuracy when doing dC demos (which is the main usecase for templates)

**Review by agnieszka-m — APPROVED** [review]

**Comment by erendabanlioglu** [comment]
@mathislucka should ve close this or merge it as you raised a point that large model would mean more cost, high latency for starting journey

**Comment by Timoeller** [comment]
since ChatGPT people are not so forgiving about bad model predictions, but maybe they are accustomed to an answer taking 1 second instead of 700ms. The answers the base model gives on industry data are often bad. We need the best extractive model out there. 

Honestly, we actually need a much better model that the current deberta-large (but this is the best we have for now). Julian and Seb are working on improvements to our extractive QA models

**Comment by sjrl** [comment]
Hey how is the progress on this? I agree with @Timoeller that switching to deberta large makes sense. I often find that for new clients that are interested in extractive QA that I set up a pipeline with the best model we have (deberta-large) to demonstrate the best accuracy and quality we can achieve.

**Review by mathislucka — APPROVED** [review]

**Pull request merged**
